// All simple ISO 3166 country data
// Sorted alphabetical by country name (special characters on bottom)
const countrylist = [
  {name: "AFAfghanistan", mobilecode: "+93"},
  {name: "AXÅland Islands", mobilecode: "+358-18"},
  {name: "ALAlbania", mobilecode: "+355"},
  {name: "DZAlgeria", mobilecode: "+213"},
  {name: "ASAmerican Samoa", mobilecode: "+1-684"},
  {name: "ADAndorra", mobilecode: "+376"},
  {name: "AOAngola", mobilecode: "+244"},
  {name: "AIAnguilla", mobilecode: "+1-264"},
  {name: "AQAntarctica", mobilecode: "+"},
  {name: "AGAntigua and Barbuda", mobilecode: "+1-268"},
  {name: "ARArgentina", mobilecode: "+54"},
  {name: "AMArmenia", mobilecode: "+374"},
  {name: "AWAruba", mobilecode: "+297"},
  {name: "AUAustralia", mobilecode: "+61"},
  {name: "ATAustria", mobilecode: "+43"},
  {name: "AZAzerbaijan", mobilecode: "+994"},
  {name: "BSBahamas, The", mobilecode: "+1-242"},
  {name: "BHBahrain", mobilecode: "+973"},
  {name: "BDBangladesh", mobilecode: "+880"},
  {name: "BBBarbados", mobilecode: "+1-246"},
  {name: "BYBelarus", mobilecode: "+375"},
  {name: "BEBelgium", mobilecode: "+32"},
  {name: "BZBelize", mobilecode: "+501"},
  {name: "BJBenin", mobilecode: "+229"},
  {name: "BMBermuda", mobilecode: "+1-441"},
  {name: "BTBhutan", mobilecode: "+975"},
  {name: "VEBolivarian Republic of Venezuela", mobilecode: "+58"},
  {name: "BOBolivia", mobilecode: "+591"},
  {name: "BQBonaire, Sint Eustatius and Saba", mobilecode: "+599"},
  {name: "BABosnia and Herzegovina", mobilecode: "+387"},
  {name: "BWBotswana", mobilecode: "+267"},
  {name: "BVBouvet Island", mobilecode: "+"},
  {name: "BRBrazil", mobilecode: "+55"},
  {name: "IOBritish Indian Ocean Territory", mobilecode: "+246"},
  {name: "BNBrunei", mobilecode: "+673"},
  {name: "BGBulgaria", mobilecode: "+359"},
  {name: "BFBurkina Faso", mobilecode: "+226"},
  {name: "BIBurundi", mobilecode: "+257"},
  {name: "CVCabo Verde", mobilecode: "+238"},
  {name: "KHCambodia", mobilecode: "+855"},
  {name: "CMCameroon", mobilecode: "+237"},
  {name: "CACanada", mobilecode: "+1"},
  {name: "KYCayman Islands", mobilecode: "+1-345"},
  {name: "CFCentral African Republic", mobilecode: "+236"},
  {name: "TDChad", mobilecode: "+235"},
  {name: "CLChile", mobilecode: "+56"},
  {name: "CNChina", mobilecode: "+86"},
  {name: "CXChristmas Island", mobilecode: "+61"},
  {name: "CCCocos (Keeling) Islands", mobilecode: "+61"},
  {name: "COColombia", mobilecode: "+57"},
  {name: "KMComoros", mobilecode: "+269"},
  {name: "CGCongo", mobilecode: "+242"},
  {name: "CDCongo (DRC)", mobilecode: "+243"},
  {name: "CKCook Islands", mobilecode: "+682"},
  {name: "CRCosta Rica", mobilecode: "+506"},
  {name: "CICôte d'Ivoire", mobilecode: "+225"},
  {name: "HRCroatia", mobilecode: "+385"},
  {name: "CUCuba", mobilecode: "+53"},
  {name: "CWCuraçao", mobilecode: "+599"},
  {name: "CYCyprus", mobilecode: "+357"},
  {name: "CZCzech Republic", mobilecode: "+420"},
  {name: "TLDemocratic Republic of Timor-Leste", mobilecode: "+670"},
  {name: "DKDenmark", mobilecode: "+45"},
  {name: "DJDjibouti", mobilecode: "+253"},
  {name: "DMDominica", mobilecode: "+1-767"},
  {name: "DODominican Republic", mobilecode: "+1-809 and 1-829"},
  {name: "ECEcuador", mobilecode: "+593"},
  {name: "EGEgypt", mobilecode: "+20"},
  {name: "SVEl Salvador", mobilecode: "+503"},
  {name: "GQEquatorial Guinea", mobilecode: "+240"},
  {name: "EREritrea", mobilecode: "+291"},
  {name: "EEEstonia", mobilecode: "+372"},
  {name: "ETEthiopia", mobilecode: "+251"},
  {name: "FKFalkland Islands (Islas Malvinas)", mobilecode: "+500"},
  {name: "FOFaroe Islands", mobilecode: "+298"},
  {name: "FJFiji Islands", mobilecode: "+679"},
  {name: "FIFinland", mobilecode: "+358"},
  {name: "FRFrance", mobilecode: "+33"},
  {name: "GFFrench Guiana", mobilecode: "+594"},
  {name: "PFFrench Polynesia", mobilecode: "+689"},
  {name: "TFFrench Southern and Antarctic Lands", mobilecode: "+"},
  {name: "GAGabon", mobilecode: "+241"},
  {name: "GMGambia, The", mobilecode: "+220"},
  {name: "GEGeorgia", mobilecode: "+995"},
  {name: "DEGermany", mobilecode: "+49"},
  {name: "GHGhana", mobilecode: "+233"},
  {name: "GIGibraltar", mobilecode: "+350"},
  {name: "GRGreece", mobilecode: "+30"},
  {name: "GLGreenland", mobilecode: "+299"},
  {name: "GDGrenada", mobilecode: "+1-473"},
  {name: "GPGuadeloupe", mobilecode: "+590"},
  {name: "GUGuam", mobilecode: "+1-671"},
  {name: "GTGuatemala", mobilecode: "+502"},
  {name: "GGGuernsey", mobilecode: "+44-1481"},
  {name: "GNGuinea", mobilecode: "+224"},
  {name: "GWGuinea-Bissau", mobilecode: "+245"},
  {name: "GYGuyana", mobilecode: "+592"},
  {name: "HTHaiti", mobilecode: "+509"},
  {name: "HMHeard Island and McDonald Islands", mobilecode: "+ "},
  {name: "HNHonduras", mobilecode: "+504"},
  {name: "HKHong Kong SAR", mobilecode: "+852"},
  {name: "HUHungary", mobilecode: "+36"},
  {name: "ISIceland", mobilecode: "+354"},
  {name: "INIndia", mobilecode: "+91"},
  {name: "IDIndonesia", mobilecode: "+62"},
  {name: "IRIran", mobilecode: "+98"},
  {name: "IQIraq", mobilecode: "+964"},
  {name: "IEIreland", mobilecode: "+353"},
  {name: "ILIsrael", mobilecode: "+972"},
  {name: "ITItaly", mobilecode: "+39"},
  {name: "JMJamaica", mobilecode: "+1-876"},
  {name: "SJJan Mayen", mobilecode: "+47"},
  {name: "JPJapan", mobilecode: "+81"},
  {name: "JEJersey", mobilecode: "+44-1534"},
  {name: "JOJordan", mobilecode: "+962"},
  {name: "KZKazakhstan", mobilecode: "+7"},
  {name: "KEKenya", mobilecode: "+254"},
  {name: "KIKiribati", mobilecode: "+686"},
  {name: "KRKorea", mobilecode: "+82"},
  {name: "XKKosovo", mobilecode: "+"},
  {name: "KWKuwait", mobilecode: "+965"},
  {name: "KGKyrgyzstan", mobilecode: "+996"},
  {name: "LALaos", mobilecode: "+856"},
  {name: "LVLatvia", mobilecode: "+371"},
  {name: "LBLebanon", mobilecode: "+961"},
  {name: "LSLesotho", mobilecode: "+266"},
  {name: "LRLiberia", mobilecode: "+231"},
  {name: "LYLibya", mobilecode: "+218"},
  {name: "LILiechtenstein", mobilecode: "+423"},
  {name: "LTLithuania", mobilecode: "+370"},
  {name: "LULuxembourg", mobilecode: "+352"},
  {name: "MOMacao SAR", mobilecode: "+853"},
  {name: "MKMacedonia, Former Yugoslav Republic of", mobilecode: "+389"},
  {name: "MGMadagascar", mobilecode: "+261"},
  {name: "MWMalawi", mobilecode: "+265"},
  {name: "MYMalaysia", mobilecode: "+60"},
  {name: "MVMaldives", mobilecode: "+960"},
  {name: "MLMali", mobilecode: "+223"},
  {name: "MTMalta", mobilecode: "+356"},
  {name: "IMMan, Isle of", mobilecode: "+44-1624"},
  {name: "MHMarshall Islands", mobilecode: "+692"},
  {name: "MQMartinique", mobilecode: "+596"},
  {name: "MRMauritania", mobilecode: "+222"},
  {name: "MUMauritius", mobilecode: "+230"},
  {name: "YTMayotte", mobilecode: "+262"},
  {name: "MXMexico", mobilecode: "+52"},
  {name: "FMMicronesia", mobilecode: "+691"},
  {name: "MDMoldova", mobilecode: "+373"},
  {name: "MCMonaco", mobilecode: "+377"},
  {name: "MNMongolia", mobilecode: "+976"},
  {name: "MEMontenegro", mobilecode: "+382"},
  {name: "MSMontserrat", mobilecode: "+1-664"},
  {name: "MAMorocco", mobilecode: "+212"},
  {name: "MZMozambique", mobilecode: "+258"},
  {name: "MMMyanmar", mobilecode: "+95"},
  {name: "NANamibia", mobilecode: "+264"},
  {name: "NRNauru", mobilecode: "+674"},
  {name: "NPNepal", mobilecode: "+977"},
  {name: "NLNetherlands", mobilecode: "+31"},
  {name: "NCNew Caledonia", mobilecode: "+687"},
  {name: "NZNew Zealand", mobilecode: "+64"},
  {name: "NINicaragua", mobilecode: "+505"},
  {name: "NENiger", mobilecode: "+227"},
  {name: "NGNigeria", mobilecode: "+234"},
  {name: "NUNiue", mobilecode: "+683"},
  {name: "NFNorfolk Island", mobilecode: "+672"},
  {name: "KPNorth Korea", mobilecode: "+850"},
  {name: "MPNorthern Mariana Islands", mobilecode: "+1-670"},
  {name: "NONorway", mobilecode: "+47"},
  {name: "OMOman", mobilecode: "+968"},
  {name: "PKPakistan", mobilecode: "+92"},
  {name: "PWPalau", mobilecode: "+680"},
  {name: "PSPalestinian Authority", mobilecode: "+970"},
  {name: "PAPanama", mobilecode: "+507"},
  {name: "PGPapua New Guinea", mobilecode: "+675"},
  {name: "PYParaguay", mobilecode: "+595"},
  {name: "PEPeru", mobilecode: "+51"},
  {name: "PHPhilippines", mobilecode: "+63"},
  {name: "PNPitcairn Islands", mobilecode: "+870"},
  {name: "PLPoland", mobilecode: "+48"},
  {name: "PTPortugal",mobilecode: "+351"},
  {name: "PRPuerto Rico", mobilecode: "+1-787 and 1-939"},
  {name: "QAQatar", mobilecode: "+974"},
  {name: "REReunion", mobilecode: "+262"},
  {name: "RORomania", mobilecode: "+40"},
  {name: "RURussia", mobilecode: "+7"},
  {name: "RWRwanda", mobilecode: "+250"},
  {name: "BLSaint Barthélemy", mobilecode: "+590"},
  {name: "SHSaint Helena, Ascension and Tristan da Cunha",mobilecode: "+290"},
  {name: "KNSaint Kitts and Nevis", mobilecode: "+1-869"},
  {name: "LCSaint Lucia", mobilecode: "+1-758"},
  {name: "MFSaint Martin (French part)", mobilecode: "+590"},
  {name: "PMSaint Pierre and Miquelon", mobilecode: "+508"},
  {name: "VCSaint Vincent and the Grenadines", mobilecode: "+1-784"},
  {name: "WSSamoa", mobilecode: "+685"},
  {name: "SMSan Marino", mobilecode: "+378"},
  {name: "STSão Tomé and Príncipe",mobilecode: "+239"},
  {name: "SASaudi Arabia", mobilecode: "+966"},
  {name: "SNSenegal",mobilecode: "+221"},
  {name: "RSSerbia", mobilecode: "+381"},
  {name: "SCSeychelles", mobilecode: "+248"},
  {name: "SLSierra Leone",mobilecode: "+232"},
  {name: "SGSingapore", mobilecode: "+65"},
  {name: "SXSint Maarten (Dutch part)", mobilecode: "+599"},
  {name: "SKSlovakia", mobilecode: "+421"},
  {name: "SISlovenia", mobilecode: "+386"},
  {name: "SBSolomon Islands", mobilecode: "+677"},
  {name: "SOSomalia", mobilecode: "+252"},
  {name: "ZASouth Africa", mobilecode: "+27"},
  {name: "GSSouth Georgia and the South Sandwich Islands", mobilecode: "+"},
  {name: "SSSouth Sudan", mobilecode: "+211"},
  {name: "ESSpain", mobilecode: "+34"},
  {name: "LKSri Lanka", mobilecode: "+94"},
  {name: "SDSudan", mobilecode: "+249"},
  {name: "SRSuriname", mobilecode: "+597"},
  {name: "SJSvalbard", mobilecode: "+47"},
  {name: "SZSwaziland", mobilecode: "+268"},
  {name: "SESweden", mobilecode: "+46"},
  {name: "CHSwitzerland", mobilecode: "+41"},
  {name: "SYSyria", mobilecode: "+963"},
  {name: "TWTaiwan", mobilecode: "+886"},
  {name: "TJTajikistan", mobilecode: "+992"},
  {name: "TZTanzania", mobilecode: "+255"},
  {name: "THThailand", mobilecode: "+66"},
  {name: "TGTogo",mobilecode: "+228"},
  {name: "TKTokelau", mobilecode: "+690"},
  {name: "TOTonga", mobilecode: "+676"},
  {name: "TTTrinidad and Tobago", mobilecode: "+1-868"},
  {name: "TNTunisia", mobilecode: "+216"},
  {name: "TRTurkey", mobilecode: "+90"},
  {name: "TMTurkmenistan", mobilecode: "+993"},
  {name: "TCTurks and Caicos Islands", mobilecode: "+1-649"},
  {name: "TVTuvalu", mobilecode: "+688"},
  {name: "UMU.S. Minor Outlying Islands", mobilecode: "+1"},
  {name: "UGUganda", mobilecode: "+256"},
  {name: "UAUkraine", mobilecode: "+380"},
  {name: "AEUnited Arab Emirates", mobilecode: "+971"},
  {name: "GBUnited Kingdom",mobilecode: "+44"},
  {name: "USUnited States", mobilecode: "+1"},
  {name: "UYUruguay", mobilecode: "+598"},
  {name: "UZUzbekistan", mobilecode: "+998"},
  {name: "VUVanuatu", mobilecode: "+678"},
  {name: "VAVatican City", mobilecode: "+379"},
  {name: "VNVietnam", mobilecode: "+84"},
  {name: "VIVirgin Islands, U.S.", mobilecode: "+1-340"},
  {name: "VGVirgin Islands, British", mobilecode: "+1-284"},
  {name: "WFWallis and Futuna", mobilecode: "+681"},
  {name: "YEYemen", mobilecode: "+967"},
  {name: "ZMZambia", mobilecode: "+260"},
  {name: "ZWZimbabwe", mobilecode: "+263"}
]
